function Help = setHelp
Help.Variables ...
 = ["N := 50 =: #Frames"  "M := 3 =: #Emitters"   "K := {Simulation: 1000, Inference: 5} =: #Samples per Frame"   ...
    "D := 5⋅10⁻²[μm²/s] =: Diffusion Coefficient"  "h := 10⁴[ɣ/s] =: Emitter Photon Flux"                         ...
    "F := 10⁵[ɣ/μm²s] =: Background Photon Flux"  "f := 2 =: EMCCD Excess Noise Factor"  "G := 0.3 =: EMCCD Gain" ...
    "δ  =: dimensionless composite trapezoidal quadrature coefficients."]                                           ;
Help.Jargon  ...
 = ["EMCCD =: Electron-Multiplying Charge-Coupled Device"    "CMOS =: Complementary Metal Oxide Semiconductor"   ...
    "SPAD =: ... "    "LINC =:"    ]                                                                               ;
end
