function RadialVector = unitSphere(Azimuth,Zenith)
         Radius       = 1         ;
         RadialVector = Radius  ...
                      * [cos(Azimuth)*sin(Zenith); ...
                         cos(Azimuth)*sin(Zenith); ...
                                      cos(Zenith)]   ;
end