function                                            ...
logL = logLikelihoodGamma(measurements,alpha,beta)
logL = sum(logpdfGamma(measurements,alpha,beta),"All");
end
%{
logL = (alpha-1) * sum(log(measurements))     ...
     - numel(measurements)                    ...
     *  ( alpha*log(beta)  - gammaln(alpha) ) ...
     -  1/beta * sum( measurements )            ;
%}
%{
logL = -numel(measurements)*log( beta^alpha * gamma(alpha) )...
     +  (alpha-1-1/beta) * sum(measurements);
%}