function                                              ...
logL = logLikelihoodInverseGamma(measurements,alpha,beta)
logL = sum(logpdfInverseGamma(measurements,alpha,beta),"All");
%{
logL = -(alpha+1) * sum(log(measurements))            ...
     + numel(measurements)                            ...
     *  ( alpha*log(beta)  - gammaln(alpha) )         ...
     -  beta * sum( 1 ./ measurements )                 ;
%}
end
