function                                                         ...
logPDF = logpdfNormal(variable,mean,variance)
         if isnumeric(variable)                                  ...
          & isnumeric(mean)                                      ...
          & isnumeric(variance)
             if ~isreal(variable)                                ...
              | ~isreal(mean)                                    ...
              | ~isreal(variance)                                ...
              |  isNegative(variance)                            ...
              |  isZed(variance)                                    %#ok<*OR2> ∵ Nonscalar.
               disp("<Normal>InvalidInputDomain: "               ...
                    + "∃ ℕ(r;μ,σ) ∀ r,μ∈ℝ,σ∈ℝ(0,∞).")             ;
               logPDF = NaN                                        ;
               return
             else
               logPDF = log(normpdf(variable,mean,sqrt(variance))) ;
               if~isnan(logPDF) & abs(logPDF) ~= Inf;  return;  end %#ok<*AND2> ∵ Nonscalar.
            end
         end
%      assume(variable,"real"); assume(mean,"real"); 
%                               assume(variance>0) ;
logPDF = - (variable - mean) .^2                 ...
      ./ ( 2 * variance )                        ...
       - 1/2 * ( log(2*pi*variance) )              ;
end