function                                         ...
logPDF = logpdfBernoulli(successProbability,outcome)
         if isnumeric(successProbability)
            if      successProbability<0         ...
             |      successProbability>1         ...
             | imag(successProbability)>0           %#ok<*OR2>
               disp("<Bernoulli>InvalidDomain:"  ...
                    + " ∃ ℙ(p) ∀ p∈ℝ[0,1]. ")      ;
               logPDF = NaN                        ;
               return
            end
         end
logPDF = outcome .* log(successProbability)       ...
       - log(1-successProbability) .* (outcome-1)   ;
end