function PDF = pdfGaussian(variable,mean,standardDeviation)
      if isnumeric(variable) & isnumeric(mean) & isnumeric(standardDeviation)
         if ~isreal(variable)                        ...
          | ~isreal(mean)                            ...
          | ~isreal(standardDeviation)               ...
          |  isNegative(standardDeviation)             %#ok<*OR2>
                disp("<Normal>InvalidInputDomain: "  ...
                     + "∃ ℕ(μ,σ) ∀ μ∈ℝ,σ∈ℝ(0,∞). ")   ;
                return
         end
      end
PDF = 1 / sqrt( 2*pi * standardDeviation^2) ...
    * exp( -(variable - mean).^2            ... 
    / (2 * standardDeviation^2))              ;
end