function                                            ...
PDF = pdfNormal(variable,mean,variance)
      if isnumeric(variable)                        ...
       & isnumeric(mean)                            ...
       & isnumeric(variance)
        if ~isreal(variable)                        ...
         | ~isreal(mean)                            ...
         | ~isreal(variance)                        ...
         |  isNegative(variance)                       %#ok<*OR2>
            disp("<Normal>InvalidInputDomain: "     ...
                 + "∃ ℕ(r;μ,σ²) ∀ r,μ∈ℝ,σ∈ℝ(0,∞).")  ;
            PDF = NaN;
        else 
            PDF = normpdf(variable,mean,sqrt(variance));
        end
        return
      end
PDF = 1 ./ sqrt( 2 .* pi .* variance)            ...
    .* exp( -(variable - mean) .^2               ...
            ./ (2 .* variance))                    ;
end